export type Word = { cn: string; py: string; en: string };
export type Category = { name: string; emoji: string; words: Word[] };

const categories: Category[] = [
    {
        name: "Greetings", emoji: "👋", words: [
            { cn: "你好", py: "nǐ hǎo", en: "hello" },
            { cn: "您好", py: "nín hǎo", en: "hello (polite)" },
            { cn: "早上好", py: "zǎoshang hǎo", en: "good morning" },
            { cn: "下午好", py: "xiàwǔ hǎo", en: "good afternoon" },
            { cn: "晚上好", py: "wǎnshang hǎo", en: "good evening" },
            { cn: "嗨", py: "hāi", en: "hi" },
            { cn: "好久不见", py: "hǎojiǔ bújiàn", en: "long time no see" },
        ],
    },
    {
        name: "Introductions", emoji: "🙋", words: [
            { cn: "我叫…", py: "wǒ jiào…", en: "my name is…" },
            { cn: "你叫什么名字", py: "nǐ jiào shénme míngzi", en: "what's your name?" },
            { cn: "认识你很高兴", py: "rènshi nǐ hěn gāoxìng", en: "nice to meet you" },
            { cn: "我是中国人", py: "wǒ shì zhōngguó rén", en: "I am Chinese" },
            { cn: "你是哪里人", py: "nǐ shì nǎlǐ rén", en: "where are you from?" },
            { cn: "我住在…", py: "wǒ zhù zài…", en: "I live in…" },
        ],
    },
    {
        name: "Polite Words", emoji: "🙏", words: [
            { cn: "谢谢", py: "xièxie", en: "thank you" },
            { cn: "不客气", py: "bú kèqi", en: "you're welcome" },
            { cn: "对不起", py: "duìbuqǐ", en: "sorry" },
            { cn: "没关系", py: "méi guānxi", en: "it's okay" },
            { cn: "请", py: "qǐng", en: "please" },
            { cn: "麻烦你", py: "máfan nǐ", en: "excuse me (to trouble you)" },
        ],
    },
    {
        name: "How Are You?", emoji: "😊", words: [
            { cn: "你好吗", py: "nǐ hǎo ma", en: "how are you?" },
            { cn: "我很好", py: "wǒ hěn hǎo", en: "I'm fine" },
            { cn: "你呢", py: "nǐ ne", en: "and you?" },
            { cn: "还好", py: "hái hǎo", en: "not bad" },
            { cn: "最近怎么样", py: "zuìjìn zěnmeyàng", en: "how have you been?" },
            { cn: "挺好的", py: "tǐng hǎo de", en: "pretty good" },
        ],
    },
    {
        name: "Goodbye", emoji: "👋", words: [
            { cn: "再见", py: "zàijiàn", en: "goodbye" },
            { cn: "拜拜", py: "báibái", en: "bye-bye" },
            { cn: "明天见", py: "míngtiān jiàn", en: "see you tomorrow" },
            { cn: "下次见", py: "xià cì jiàn", en: "see you next time" },
            { cn: "晚安", py: "wǎn'ān", en: "good night" },
            { cn: "慢走", py: "màn zǒu", en: "take care (when leaving)" },
        ],
    },
    {
        name: "Small Talk", emoji: "💬", words: [
            { cn: "你喜欢什么", py: "nǐ xǐhuan shénme", en: "what do you like?" },
            { cn: "今天天气很好", py: "jīntiān tiānqì hěn hǎo", en: "the weather is nice today" },
            { cn: "你吃了吗", py: "nǐ chī le ma", en: "have you eaten?" },
            { cn: "你在做什么", py: "nǐ zài zuò shénme", en: "what are you doing?" },
            { cn: "你几岁", py: "nǐ jǐ suì", en: "how old are you?" },
            { cn: "你的爱好是什么", py: "nǐ de àihào shì shénme", en: "what's your hobby?" },
        ],
    },
    {
        name: "Asking for Help", emoji: "🆘", words: [
            { cn: "请问", py: "qǐngwèn", en: "may I ask…" },
            { cn: "你能帮我吗", py: "nǐ néng bāng wǒ ma", en: "can you help me?" },
            { cn: "这个怎么说", py: "zhège zěnme shuō", en: "how do you say this?" },
            { cn: "我听不懂", py: "wǒ tīng bù dǒng", en: "I don't understand" },
            { cn: "请再说一次", py: "qǐng zài shuō yí cì", en: "please say it again" },
            { cn: "慢一点", py: "màn yìdiǎn", en: "slower please" },
        ],
    },
    {
        name: "Numbers", emoji: "🔢", words: [
            { cn: "一", py: "yī", en: "one" },
            { cn: "二", py: "èr", en: "two" },
            { cn: "三", py: "sān", en: "three" },
            { cn: "四", py: "sì", en: "four" },
            { cn: "五", py: "wǔ", en: "five" },
            { cn: "六", py: "liù", en: "six" },
            { cn: "七", py: "qī", en: "seven" },
            { cn: "八", py: "bā", en: "eight" },
            { cn: "九", py: "jiǔ", en: "nine" },
            { cn: "十", py: "shí", en: "ten" },
            { cn: "百", py: "bǎi", en: "hundred" },
            { cn: "千", py: "qiān", en: "thousand" },
        ],
    },
    {
        name: "Family", emoji: "👨‍👩‍👧‍👦", words: [
            { cn: "爸爸", py: "bàba", en: "dad" },
            { cn: "妈妈", py: "māma", en: "mom" },
            { cn: "哥哥", py: "gēge", en: "older brother" },
            { cn: "姐姐", py: "jiějie", en: "older sister" },
            { cn: "弟弟", py: "dìdi", en: "younger brother" },
            { cn: "妹妹", py: "mèimei", en: "younger sister" },
            { cn: "爷爷", py: "yéye", en: "grandpa (paternal)" },
            { cn: "奶奶", py: "nǎinai", en: "grandma (paternal)" },
            { cn: "你家有几口人", py: "nǐ jiā yǒu jǐ kǒu rén", en: "how many people in your family?" },
        ],
    },
    {
        name: "Food & Drink", emoji: "🍜", words: [
            { cn: "米饭", py: "mǐfàn", en: "rice" },
            { cn: "面条", py: "miàntiáo", en: "noodles" },
            { cn: "饺子", py: "jiǎozi", en: "dumplings" },
            { cn: "包子", py: "bāozi", en: "steamed bun" },
            { cn: "茶", py: "chá", en: "tea" },
            { cn: "水", py: "shuǐ", en: "water" },
            { cn: "牛奶", py: "niúnǎi", en: "milk" },
            { cn: "水果", py: "shuǐguǒ", en: "fruit" },
            { cn: "好吃", py: "hǎochī", en: "delicious" },
            { cn: "我饿了", py: "wǒ è le", en: "I'm hungry" },
            { cn: "我渴了", py: "wǒ kě le", en: "I'm thirsty" },
        ],
    },
    {
        name: "Time", emoji: "🕐", words: [
            { cn: "今天", py: "jīntiān", en: "today" },
            { cn: "明天", py: "míngtiān", en: "tomorrow" },
            { cn: "昨天", py: "zuótiān", en: "yesterday" },
            { cn: "现在", py: "xiànzài", en: "now" },
            { cn: "早上", py: "zǎoshang", en: "morning" },
            { cn: "中午", py: "zhōngwǔ", en: "noon" },
            { cn: "下午", py: "xiàwǔ", en: "afternoon" },
            { cn: "晚上", py: "wǎnshang", en: "evening" },
            { cn: "几点了", py: "jǐ diǎn le", en: "what time is it?" },
            { cn: "星期几", py: "xīngqī jǐ", en: "what day of the week?" },
        ],
    },
    {
        name: "Directions", emoji: "🧭", words: [
            { cn: "左", py: "zuǒ", en: "left" },
            { cn: "右", py: "yòu", en: "right" },
            { cn: "前面", py: "qiánmiàn", en: "in front" },
            { cn: "后面", py: "hòumiàn", en: "behind" },
            { cn: "上面", py: "shàngmiàn", en: "above" },
            { cn: "下面", py: "xiàmiàn", en: "below" },
            { cn: "这里", py: "zhèlǐ", en: "here" },
            { cn: "那里", py: "nàlǐ", en: "there" },
            { cn: "厕所在哪里", py: "cèsuǒ zài nǎlǐ", en: "where is the restroom?" },
            { cn: "怎么走", py: "zěnme zǒu", en: "how to get there?" },
        ],
    },
    {
        name: "Shopping", emoji: "🛒", words: [
            { cn: "多少钱", py: "duōshao qián", en: "how much?" },
            { cn: "太贵了", py: "tài guì le", en: "too expensive" },
            { cn: "便宜一点", py: "piányi yìdiǎn", en: "a bit cheaper" },
            { cn: "我要这个", py: "wǒ yào zhège", en: "I want this one" },
            { cn: "可以试试吗", py: "kěyǐ shìshi ma", en: "can I try it?" },
            { cn: "买单", py: "mǎidān", en: "check please" },
            { cn: "大", py: "dà", en: "big / large" },
            { cn: "小", py: "xiǎo", en: "small" },
        ],
    },
    {
        name: "Feelings", emoji: "😄", words: [
            { cn: "开心", py: "kāixīn", en: "happy" },
            { cn: "难过", py: "nánguò", en: "sad" },
            { cn: "生气", py: "shēngqì", en: "angry" },
            { cn: "害怕", py: "hàipà", en: "scared" },
            { cn: "累", py: "lèi", en: "tired" },
            { cn: "无聊", py: "wúliáo", en: "bored" },
            { cn: "紧张", py: "jǐnzhāng", en: "nervous" },
            { cn: "兴奋", py: "xīngfèn", en: "excited" },
        ],
    },
    {
        name: "Weather", emoji: "🌤", words: [
            { cn: "天气", py: "tiānqì", en: "weather" },
            { cn: "热", py: "rè", en: "hot" },
            { cn: "冷", py: "lěng", en: "cold" },
            { cn: "下雨", py: "xià yǔ", en: "raining" },
            { cn: "下雪", py: "xià xuě", en: "snowing" },
            { cn: "晴天", py: "qíngtiān", en: "sunny day" },
            { cn: "刮风", py: "guā fēng", en: "windy" },
            { cn: "多云", py: "duō yún", en: "cloudy" },
        ],
    },
    {
        name: "School", emoji: "🏫", words: [
            { cn: "学校", py: "xuéxiào", en: "school" },
            { cn: "老师", py: "lǎoshī", en: "teacher" },
            { cn: "学生", py: "xuéshēng", en: "student" },
            { cn: "同学", py: "tóngxué", en: "classmate" },
            { cn: "上课", py: "shàng kè", en: "attend class" },
            { cn: "下课", py: "xià kè", en: "class is over" },
            { cn: "作业", py: "zuòyè", en: "homework" },
            { cn: "考试", py: "kǎoshì", en: "exam" },
            { cn: "书", py: "shū", en: "book" },
        ],
    },
    {
        name: "Compliments", emoji: "🌟", words: [
            { cn: "你真棒", py: "nǐ zhēn bàng", en: "you're awesome" },
            { cn: "你真聪明", py: "nǐ zhēn cōngming", en: "you're so smart" },
            { cn: "太厉害了", py: "tài lìhai le", en: "so impressive" },
            { cn: "你很漂亮", py: "nǐ hěn piàoliang", en: "you're beautiful" },
            { cn: "做得好", py: "zuò de hǎo", en: "well done" },
            { cn: "加油", py: "jiāyóu", en: "keep it up / go for it" },
        ],
    },
    {
        name: "Body Parts", emoji: "🦶", words: [
            { cn: "头", py: "tóu", en: "head" },
            { cn: "头发", py: "tóufa", en: "hair" },
            { cn: "眼睛", py: "yǎnjing", en: "eyes" },
            { cn: "耳朵", py: "ěrduo", en: "ears" },
            { cn: "鼻子", py: "bízi", en: "nose" },
            { cn: "嘴巴", py: "zuǐba", en: "mouth" },
            { cn: "牙齿", py: "yáchǐ", en: "teeth" },
            { cn: "手", py: "shǒu", en: "hand" },
            { cn: "脚", py: "jiǎo", en: "foot" },
            { cn: "肚子", py: "dùzi", en: "belly" },
            { cn: "腿", py: "tuǐ", en: "leg" },
            { cn: "背", py: "bèi", en: "back" },
        ],
    },
    {
        name: "Jobs", emoji: "👷", words: [
            { cn: "老师", py: "lǎoshī", en: "teacher" },
            { cn: "医生", py: "yīshēng", en: "doctor" },
            { cn: "护士", py: "hùshi", en: "nurse" },
            { cn: "警察", py: "jǐngchá", en: "police officer" },
            { cn: "消防员", py: "xiāofángyuán", en: "firefighter" },
            { cn: "厨师", py: "chúshī", en: "chef" },
            { cn: "司机", py: "sījī", en: "driver" },
            { cn: "农民", py: "nóngmín", en: "farmer" },
            { cn: "工程师", py: "gōngchéngshī", en: "engineer" },
            { cn: "科学家", py: "kēxuéjiā", en: "scientist" },
            { cn: "宇航员", py: "yǔhángyuán", en: "astronaut" },
        ],
    },
    {
        name: "Animals", emoji: "🐾", words: [
            { cn: "猫", py: "māo", en: "cat" },
            { cn: "狗", py: "gǒu", en: "dog" },
            { cn: "鱼", py: "yú", en: "fish" },
            { cn: "鸟", py: "niǎo", en: "bird" },
            { cn: "兔子", py: "tùzi", en: "rabbit" },
            { cn: "马", py: "mǎ", en: "horse" },
            { cn: "牛", py: "niú", en: "cow" },
            { cn: "猪", py: "zhū", en: "pig" },
            { cn: "鸡", py: "jī", en: "chicken" },
            { cn: "老虎", py: "lǎohǔ", en: "tiger" },
            { cn: "大象", py: "dàxiàng", en: "elephant" },
            { cn: "猴子", py: "hóuzi", en: "monkey" },
        ],
    },
    {
        name: "Colors", emoji: "🎨", words: [
            { cn: "红色", py: "hóngsè", en: "red" },
            { cn: "蓝色", py: "lánsè", en: "blue" },
            { cn: "绿色", py: "lǜsè", en: "green" },
            { cn: "黄色", py: "huángsè", en: "yellow" },
            { cn: "白色", py: "báisè", en: "white" },
            { cn: "黑色", py: "hēisè", en: "black" },
            { cn: "粉色", py: "fěnsè", en: "pink" },
            { cn: "紫色", py: "zǐsè", en: "purple" },
            { cn: "橙色", py: "chéngsè", en: "orange" },
        ],
    },
    {
        name: "Fruits", emoji: "🍎", words: [
            { cn: "苹果", py: "píngguǒ", en: "apple" },
            { cn: "香蕉", py: "xiāngjiāo", en: "banana" },
            { cn: "西瓜", py: "xīguā", en: "watermelon" },
            { cn: "草莓", py: "cǎoméi", en: "strawberry" },
            { cn: "葡萄", py: "pútao", en: "grape" },
            { cn: "橘子", py: "júzi", en: "orange" },
            { cn: "桃子", py: "táozi", en: "peach" },
            { cn: "芒果", py: "mángguǒ", en: "mango" },
        ],
    },
    {
        name: "Transport", emoji: "🚗", words: [
            { cn: "汽车", py: "qìchē", en: "car" },
            { cn: "公共汽车", py: "gōnggòng qìchē", en: "bus" },
            { cn: "火车", py: "huǒchē", en: "train" },
            { cn: "飞机", py: "fēijī", en: "airplane" },
            { cn: "自行车", py: "zìxíngchē", en: "bicycle" },
            { cn: "地铁", py: "dìtiě", en: "subway" },
            { cn: "船", py: "chuán", en: "boat" },
            { cn: "出租车", py: "chūzūchē", en: "taxi" },
        ],
    },
    {
        name: "Actions", emoji: "🏃", words: [
            { cn: "吃", py: "chī", en: "eat" },
            { cn: "喝", py: "hē", en: "drink" },
            { cn: "跑", py: "pǎo", en: "run" },
            { cn: "走", py: "zǒu", en: "walk" },
            { cn: "跳", py: "tiào", en: "jump" },
            { cn: "看", py: "kàn", en: "look / watch" },
            { cn: "听", py: "tīng", en: "listen" },
            { cn: "说", py: "shuō", en: "speak" },
            { cn: "读", py: "dú", en: "read" },
            { cn: "写", py: "xiě", en: "write" },
            { cn: "画", py: "huà", en: "draw" },
            { cn: "唱", py: "chàng", en: "sing" },
            { cn: "睡觉", py: "shuìjiào", en: "sleep" },
        ],
    },
    {
        name: "Places", emoji: "🏠", words: [
            { cn: "家", py: "jiā", en: "home" },
            { cn: "学校", py: "xuéxiào", en: "school" },
            { cn: "医院", py: "yīyuàn", en: "hospital" },
            { cn: "超市", py: "chāoshì", en: "supermarket" },
            { cn: "公园", py: "gōngyuán", en: "park" },
            { cn: "图书馆", py: "túshūguǎn", en: "library" },
            { cn: "餐厅", py: "cāntīng", en: "restaurant" },
            { cn: "银行", py: "yínháng", en: "bank" },
            { cn: "机场", py: "jīchǎng", en: "airport" },
        ],
    },
    {
        name: "Clothes", emoji: "👕", words: [
            { cn: "衣服", py: "yīfu", en: "clothes" },
            { cn: "裤子", py: "kùzi", en: "pants" },
            { cn: "裙子", py: "qúnzi", en: "skirt / dress" },
            { cn: "鞋子", py: "xiézi", en: "shoes" },
            { cn: "帽子", py: "màozi", en: "hat" },
            { cn: "袜子", py: "wàzi", en: "socks" },
            { cn: "外套", py: "wàitào", en: "jacket / coat" },
        ],
    },
    {
        name: "In the House", emoji: "🏠", words: [
            { cn: "桌子", py: "zhuōzi", en: "table" },
            { cn: "椅子", py: "yǐzi", en: "chair" },
            { cn: "床", py: "chuáng", en: "bed" },
            { cn: "沙发", py: "shāfā", en: "sofa" },
            { cn: "电视", py: "diànshì", en: "TV" },
            { cn: "电脑", py: "diànnǎo", en: "computer" },
            { cn: "手机", py: "shǒujī", en: "phone" },
            { cn: "窗户", py: "chuānghu", en: "window" },
            { cn: "门", py: "mén", en: "door" },
            { cn: "灯", py: "dēng", en: "light / lamp" },
            { cn: "冰箱", py: "bīngxiāng", en: "fridge" },
            { cn: "杯子", py: "bēizi", en: "cup" },
            { cn: "碗", py: "wǎn", en: "bowl" },
            { cn: "筷子", py: "kuàizi", en: "chopsticks" },
            { cn: "勺子", py: "sháozi", en: "spoon" },
            { cn: "钥匙", py: "yàoshi", en: "key" },
            { cn: "书包", py: "shūbāo", en: "schoolbag" },
            { cn: "雨伞", py: "yǔsǎn", en: "umbrella" },
        ],
    },
    {
        name: "Rooms", emoji: "🚻", words: [
            { cn: "客厅", py: "kètīng", en: "living room" },
            { cn: "卧室", py: "wòshì", en: "bedroom" },
            { cn: "厨房", py: "chúfáng", en: "kitchen" },
            { cn: "卫生间", py: "wèishēngjiān", en: "bathroom" },
            { cn: "阳台", py: "yángtái", en: "balcony" },
            { cn: "书房", py: "shūfáng", en: "study room" },
            { cn: "车库", py: "chēkù", en: "garage" },
            { cn: "花园", py: "huāyuán", en: "garden" },
        ],
    },
];

export default categories;
