const dict: Record<string, string> = {
    "的": "of, possessive particle",
    "一": "one",
    "是": "is, am, are",
    "不": "not, no",
    "了": "completed action, modal particle",
    "人": "person, people",
    "我": "I, me",
    "在": "at, in",
    "有": "have, exist",
    "他": "he, him",
    "这": "this",
    "中": "middle, center, China",
    "大": "big, large",
    "来": "come",
    "上": "up, above, on",
    "个": "measure word (general)",
    "国": "country, nation",
    "为": "for, because",
    "以": "with, by, to",
    "子": "child, son, seed",
    "到": "arrive, to, until",
    "说": "say, speak",
    "们": "plural marker (for people)",
    "生": "life, birth, raw",
    "会": "can, will, meeting",
    "自": "self, from",
    "着": "verb particle (ongoing action)",
    "去": "go, leave",
    "之": "of, possessive (classical)",
    "过": "pass, cross, experience",
    "家": "home, family",
    "学": "study, learn",
    "对": "correct, toward, pair",
    "可": "can, may",
    "她": "she, her",
    "里": "inside, mile",
    "后": "after, behind",
    "小": "small, little",
    "么": "question particle",
    "心": "heart, mind",
    "多": "many, much",
    "天": "sky, day, heaven",
    "而": "and, but, yet",
    "要": "want, need, important",
    "好": "good, well",
    "都": "all, both, capital city",
    "然": "so, like that, correct",
    "没": "not have, not",
    "成": "become, succeed",
    "日": "sun, day",
    "行": "walk, go, okay, row",
    "于": "at, in, to",
    "起": "rise, get up",
    "也": "also, too",
    "与": "and, with",
    "事": "matter, thing, affair",
    "其": "its, his, that",
    "写": "write",
    "还": "still, also, return",
    "用": "use",
    "道": "way, path, say",
    "活": "live, alive",
    "就": "then, just, at once",
    "从": "from, follow",
    "时": "time, hour",
    "合": "combine, together, fit",
    "地": "earth, ground, land",
    "出": "go out, exit",
    "年": "year",
    "开": "open, start",
    "展": "expand, exhibit",
    "理": "reason, logic, manage",
    "能": "can, able, energy",
    "作": "do, make, work",
    "区": "area, district",
    "商": "business, commerce",
    "五": "five",
    "果": "fruit, result",
    "实": "real, true, solid",
    "进": "enter, advance",
    "种": "kind, type, seed, plant",
    "现": "now, present, appear",
    "它": "it",
    "前": "front, before",
    "些": "some, a few",
    "所": "place, that which",
    "已": "already",
    "经": "pass through, scripture",
    "月": "moon, month",
    "长": "long, grow",
    "知": "know",
    "民": "people, citizen",
    "世": "world, generation",
    "最": "most",
    "手": "hand",
    "明": "bright, clear, tomorrow",
    "方": "square, direction, method",
    "报": "report, newspaper",
    "电": "electricity, lightning",
    "全": "all, whole, complete",
    "定": "decide, fix, certain",
    "己": "self, oneself",
    "花": "flower, spend",
    "看": "look, see, watch",
    "外": "outside, foreign",
    "处": "place, deal with",
    "四": "four",
    "力": "power, strength, force",
    "结": "tie, knot, result",
    "山": "mountain",
    "百": "hundred",
    "回": "return, go back, time",
    "孩": "child",
    "万": "ten thousand",
    "少": "few, little, young",
    "直": "straight, direct",
    "意": "meaning, idea, wish",
    "夜": "night",
    "比": "compare, than",
    "阶": "step, rank, stairs",
    "连": "connect, even, continuous",
    "车": "car, vehicle",
    "重": "heavy, important, again",
    "便": "convenient, then",
    "斗": "fight, struggle",
    "马": "horse",
    "哪": "which, where",
    "化": "change, transform",
    "太": "too, very, great",
    "指": "finger, point",
    "变": "change, become",
    "社": "society, organization",
    "似": "seem, like, similar",
    "士": "scholar, soldier",
    "者": "person who, -er",
    "干": "do, dry, trunk",
    "石": "stone, rock",
    "满": "full, satisfied",
    "得": "get, obtain, must",
    "式": "style, type, formula",
    "居": "live, reside",
    "批": "batch, criticize",
    "次": "time (occurrence), next",
    "亲": "parent, relative, close",
    "头": "head, top",
    "火": "fire",
    "步": "step, walk",
    "问": "ask, question",
    "喜": "happy, like, joy",
    "让": "let, allow, yield",
    "相": "each other, appearance",
    "解": "solve, untie, explain",
    "立": "stand, establish",
    "水": "water",
    "无": "without, none",
    "建": "build, construct",
    "号": "number, mark",
    "新": "new",
    "带": "belt, bring, carry",
    "列": "row, list, arrange",
    "死": "die, death",
    "尾": "tail, end",
    "张": "stretch, sheet, surname",
    "难": "difficult, hard",
    "术": "art, skill, technique",
    "言": "speech, word, say",
    "员": "member, person",
    "特": "special, particular",
    "名": "name, fame",
    "真": "true, real",
    "论": "discuss, theory",
    "走": "walk, go, leave",
    "义": "justice, meaning",
    "各": "each, every",
    "入": "enter",
    "几": "how many, several",
    "口": "mouth, opening",
    "认": "recognize, admit",
    "条": "strip, item, clause",
    "平": "flat, level, peace",
    "系": "system, connect, tie",
    "气": "air, gas, breath, anger",
    "题": "topic, question, title",
    "英": "hero, brave, English",
    "床": "bed",
    "检": "check, inspect",
    "师": "teacher, master",
    "息": "rest, breath, news",
    "引": "lead, guide, pull",
    "快": "fast, quick, happy",
    "德": "virtue, morality",
    "慢": "slow",
    "深": "deep, profound",
    "海": "sea, ocean",
    "七": "seven",
    "女": "woman, female",
    "任": "appoint, let, duty",
    "件": "piece, item, document",
    "感": "feel, sense, emotion",
    "准": "allow, accurate, standard",
    "团": "group, ball, regiment",
    "屋": "room, house",
    "离": "leave, from, distance",
    "色": "color",
    "脸": "face",
    "片": "slice, piece, film",
    "科": "science, department",
    "倒": "fall, pour, reverse",
    "睛": "eye (eyeball)",
    "利": "sharp, benefit, profit",
    "刚": "just now, hard, firm",
    "且": "and, moreover",
    "由": "from, by, reason",
    "送": "send, deliver, give",
    "切": "cut, slice, all",
    "星": "star",
    "导": "guide, lead, direct",
    "晚": "late, evening, night",
    "表": "surface, table, express",
    "够": "enough",
    "整": "whole, tidy, arrange",
    "响": "sound, ring, loud",
    "雪": "snow",
    "流": "flow, stream",
    "未": "not yet",
    "场": "field, place, scene",
    "该": "should, ought to",
    "并": "and, also, combine",
    "底": "bottom, base",
    "刻": "carve, quarter hour",
    "伟": "great, mighty",
    "忙": "busy",
    "提": "lift, raise, mention",
    "确": "true, certain, exact",
    "近": "near, close",
    "亮": "bright, light",
    "轻": "light (weight), gentle",
    "讲": "speak, tell, explain",
    "农": "farm, agriculture",
    "古": "ancient, old",
    "黑": "black, dark",
    "告": "tell, inform, announce",
    "界": "boundary, world, field",
    "拉": "pull, drag",
    "呀": "exclamation particle",
    "土": "earth, soil, land",
    "清": "clear, clean, pure",
    "阳": "sun, positive, yang",
    "照": "shine, photo, according to",
    "办": "do, handle, manage",
    "史": "history",
    "改": "change, correct, reform",
    "历": "experience, calendar",
    "转": "turn, rotate, transfer",
    "画": "draw, paint, picture",
    "造": "make, build, create",
    "嘴": "mouth, lips",
    "此": "this, here",
    "治": "govern, cure, manage",
    "北": "north",
    "必": "must, certainly",
    "服": "clothes, serve, obey",
    "雨": "rain",
    "穿": "wear, pass through",
    "内": "inside, inner",
    "识": "know, recognize",
    "验": "test, examine, verify",
    "传": "pass on, spread, biography",
    "业": "business, industry, career",
    "菜": "vegetable, dish, food",
    "爬": "climb, crawl",
    "睡": "sleep",
    "兴": "prosper, interest, mood",
    "形": "shape, form",
    "量": "measure, quantity, amount",
    "咱": "we, us (informal)",
    "观": "view, watch, concept",
    "苦": "bitter, hard, suffer",
    "体": "body, form, style",
    "众": "crowd, many, public",
    "通": "through, connect, common",
    "冲": "rush, rinse, charge",
    "破": "break, torn, defeat",
    "友": "friend",
    "度": "degree, measure, time",
    "饭": "rice, meal, food",
    "公": "public, fair, male",
    "旁": "beside, side",
    "房": "room, house",
    "极": "extreme, pole, very",
    "南": "south",
    "枪": "gun, spear",
    "读": "read",
    "沙": "sand",
    "岁": "year (age), years old",
    "线": "line, thread, wire",
    "野": "wild, field",
    "坚": "firm, hard, strong",
    "空": "empty, sky, air",
    "收": "receive, collect",
    "算": "count, calculate, plan",
    "至": "to, until, most",
    "政": "politics, government",
    "城": "city, wall",
    "劳": "labor, work, toil",
    "落": "fall, drop, land",
    "钱": "money",
    "围": "surround, encircle",
    "弟": "younger brother",
    "胸": "chest, breast",
    "乎": "particle (classical)",
    "尼": "nun, Buddhist",
    "持": "hold, keep, support",
    "西": "west",
    "括": "include, enclose",
    "志": "will, ambition, record",
    "反": "opposite, reverse, rebel",
    "尖": "sharp, pointed, tip",
    "须": "must, beard",
    "飞": "fly",
    "关": "close, shut, concern",
    "核": "core, nuclear, seed",
    "驾": "drive, ride",
    "军": "army, military",
    "工": "work, worker, craft",
    "物": "thing, object, matter",
    "广": "wide, broad, vast",
    "村": "village",
    "声": "sound, voice",
    "纸": "paper",
    "哈": "ha (laughter)",
    "元": "yuan, origin, first",
    "周": "week, circle, surname",
    "父": "father",
    "母": "mother",
    "企": "enterprise, stand on tiptoe",
    "二": "two",
    "三": "three",
    "六": "six",
    "八": "eight",
    "九": "nine",
    "十": "ten",
    "零": "zero",
    "你": "you",
    "吃": "eat",
    "喝": "drink",
    "爱": "love",
    "想": "think, want, miss",
    "做": "do, make",
    "给": "give, for",
    "叫": "call, shout, name",
    "请": "please, invite",
    "谢": "thank",
    "再": "again",
    "见": "see, meet",
    "听": "listen, hear",
    "笑": "laugh, smile",
    "哭": "cry, weep",
    "跑": "run",
    "站": "stand, station",
    "坐": "sit",
    "买": "buy",
    "卖": "sell",
    "高": "tall, high",
    "低": "low",
    "左": "left",
    "右": "right",
    "东": "east",
    "猫": "cat",
    "狗": "dog",
    "鱼": "fish",
    "鸟": "bird",
    "树": "tree",
    "草": "grass",
    "风": "wind",
    "云": "cloud",
    "河": "river",
    "路": "road, path",
    "门": "door, gate",
    "窗": "window",
    "桌": "table, desk",
    "椅": "chair",
    "书": "book, write",
    "笔": "pen, brush",
    "红": "red",
    "蓝": "blue",
    "绿": "green",
    "白": "white",
    "黄": "yellow",
    "吗": "question particle",
    "呢": "particle (and you?)",
    "啊": "exclamation particle",
    "把": "hold, handle, particle",
    "被": "by (passive), quilt",
    "跟": "follow, with",
    "很": "very",

};

export default dict;
